### ISSUE TITLE
What would be the preferred way to call GETJOB with WITHCOUNTERS?

### ISSUE THREAD

**Issue by Revisor** [mariano/disque-php#1]
Hi, the current implementation of GETJOB doesn't consider the (probably later added) argument WITHCOUNTERS. What would be the best way to call GETJOB with WITHCOUNTERS and get the whole result?

I presume the JobsResponse needs to consider the newly returned fields as well, right?

**Comment by Revisor** [comment]
I'm working on it.

**Comment by mariano** [comment]
Let me know when you have a PR ready, thanks @Revisor  :)
