### ISSUE TITLE
What's the reason for silencing errors when unserializing the job body?

### ISSUE THREAD

**Issue by Revisor** [mariano/disque-php#10]
I'm talking about [this line](https://github.com/mariano/disque-php/blob/master/src/Queue/Marshal/JobMarshaler.php#L18) in the `JobMarshaler`:

```php
$body = @json_decode($source, true);
```

Wouldn't it be better not to silence the errors so that the error handling can catch the exact reason?

**Comment by mariano** [comment]
@Revisor once again you are correct :)
