### ISSUE TITLE
Is there something else you would like to change for 2.0?

### ISSUE THREAD

**Issue by Revisor** [mariano/disque-php#15]
In #12 you mentioned that moving the connection code out of the Manager was something you had wanted to do.

Is there something else you would like to change and take advantage of the upcoming 2.0? If so, can you create issues for it?

There is always something to improve, of course, but what are the high priorities in your opinion?

Since I'm now immersed in the library, I would be glad to help you.

**Comment by mariano** [comment]
I think we are good to go to tag 2.0. What do you think?

**Comment by Revisor** [comment]
We are going to start writing production code on top of the current `master` branch next week. Even though I don't see the need right now, it is possible that we uncover a few more things and propose a few more changes.

So if you are OK with being a bit more cautious, what do you think about tagging now with a `2.0-alpha` and giving us (and others) some time to use it in the real world?

I don't want to make the release needlessly complicated but you want to follow semantic versioning (for which I'm really grateful and completely agree with your decision) and even the smallest change in any interface would mean another major version bump.

I propose tagging it `alpha` and not `beta` or `rc` because `alpha` [may still get new features](https://en.wikipedia.org/wiki/Software_release_life_cycle#Alpha) - or in our case the interface may change - while the other two are under a "feature freeze" which I understand in the context of a library as an "interface freeze".

**Comment by mariano** [comment]
@revisor hows it looking fof you now?

**Comment by mariano** [comment]
Done https://github.com/mariano/disque-php/releases/tag/2.0-alpha

**Comment by Revisor** [comment]
Great, thank you! I have already switched the dependency to `2.0-alpha`.
