### ISSUE TITLE
Add methods for working with the body, NACKs and additional deliveries to the JobInterface

### ISSUE THREAD

**Issue by Revisor** [mariano/disque-php#2]
`GETJOB` returns at least the queue, the ID and the body:

> Jobs are returned as a three elements array containing the queue name, the Job ID, and the job body itself.

What's the point of a job without a body?

Case in point:
`Disque\Queue\Marshal\JobMarshaler::marshal()` expects a `JobInterface` type, but it actually requires a `Job` type and even throws an exception, because it needs the `Job::getBody()` method.

And subquestions:

* Should we agree that there is no point of a Job without an ID and a body, shouldn't they be provided as soon as in the constructor so that the object can't be instantiated in an invalid state?
* In case the ID and the body are provided in the constructor, wouldn't it be preferrable to remove their setters and make Job immutable? What would be the use case for changing the Job ID or the body on the fly, after it has been created?

**Comment by Revisor** [comment]
I suggest the following interface:

```interface JobInterface
{
    /**
     * Get the job ID
     *
     * @return string
     */
    public function getId();

    /**
     * Get the job body
     *
     * @return array Job body
     */
    public function getBody();

    /**
     * Get the number of NACKs
     * 
     * @return int
     */
    public function getNacks();

    /**
     * Set the number of NACKs
     * 
     * @param int $nacks
     */
    public function setNacks($nacks);

    /**
     * Get the number of additional deliveries
     * 
     * @return int
     */
    public function getAdditionalDeliveries();

    /**
     * Set the number of additional deliveries
     * 
     * @param int $additionalDeliveries
     */
    public function setAdditionalDeliveries($additionalDeliveries);
}```
These are all properties of a Disque job as of now. Job ID and job body are mandatory and should be provided through a constructor. The number of NACKs and the number of additional deliveries are optional and should be provided through a setter. These two values may be read immediately from the GETJOB command (see #1), or later with the SHOW command.

What do you think?

**Comment by Revisor** [comment]
Implemented #2 and #3, what do you think?

https://github.com/Revisor/disque-php/blob/revisor/jobinterface/src/Queue/BaseJob.php

**Comment by mariano** [comment]
The reasoning is the following. I wanted the `JobInterface` to be as flexible as possible, only forcing you to implement methods that must absolutely be there for at least the pull job / push job workflow to work. The only requirement, in essence then, is the ID of a job, since that is required for a job to be marked as processed.

The documentation section entitled *Changing the Job class* showcases this, where I implement a `Job` class that actually has no body per se (the body gets built actually in the `MarshalerInterface` implementation.

This allows you to be as flexible as possible with your job implementations. However this would make perfect sense if the `JobInterface` required no method, but since the getter and setter of the id is required, as noted above, then this becomes moot.

I understand your proposal of adding more getters and setters for `NACKs` and additional deliveries, but they are not mandatory for the workflow to, well, work, and furthermore they wouldn't be used anyway, since the `GETJOB` implementation does not return an instance of `JobInterface`, but an array with information.

Thoughts @Revisor ?

**Comment by Revisor** [comment]
Ok, now I understand the reasoning behind the sparse interface.

I have gone through the code again and I would restate my suggestion as follows:

Right now there is a mismatch between the `JobInterface` and the `JobMarshaler`.

The method `MarshalerInterface::marshal()` [accepts](https://github.com/mariano/disque-php/blob/master/src/Queue/Marshal/MarshalerInterface.php#L24) a `JobInterface`. The `JobInterface` however [promises](https://github.com/mariano/disque-php/blob/master/src/Queue/JobInterface.php) only the `set/getId()` methods, while `JobMarshaler` requires the method `getBody()`. The `JobMarshaler` [guards this requirement with an exception](https://github.com/mariano/disque-php/blob/master/src/Queue/Marshal/JobMarshaler.php#L33) and thus loses the advantage of type hinting.

I think it would be useful to make use of whatever type hinting we can. The `marshal()` method should be promised a Job that actually has a `getBody()` method.

I think there are two solutions to this:

1. Create a new interface, eg. `JobWithBodyInterface`, with the `get/setBody()` methods, and change the type hint in `marshal()` to this new interface. The `Job` would then have to implement both `JobInterface` and `JobWithBodyInterface`. 
2. Add the methods `get/setBody()` to the existing `JobInterface` and leave the current type hint in `marshal()` as is.  
This would reopen my question about the type of the Job body (#3), because once defined in the interface, the type cannot be changed. In order to be as flexible as possible, the body should be of a mixed type, in my opinion.

Whatever solution you choose, I'm standing before the exactly same question when implementing `NACKs` and `additional-deliveries` (#1). How should they be type-hinted? Should I create a new interface or extend the current `JobInterface`?

If it were up to me, I would update the `JobInterface` to contain getters and setters for these properties (job, ID, nacks and additionalDeliveries). The `BaseJob` can still be very flexible but the type hint `JobInterface` would actually bear a substantial promise of an object that fully describes the Disque job. To split the behavior into multiple interfaces could pose problems, because we can only type hint one interface, while future code might require eg. both `getId()`, `getBody()` as well as `getNacks()` - for example a class deciding whether a failed job should be retried, retried with a delay, logged, or moved to a dead letter queue.

I have created as flexible an implementation of [JobInterface](https://github.com/Revisor/disque-php/blob/revisor/jobinterface/src/Queue/JobInterface.php) and [BaseJob](https://github.com/Revisor/disque-php/blob/revisor/jobinterface/src/Queue/BaseJob.php) as possible in my branch as a showcase.

* You can create a Job with just a body (eg. when creating a new Job)
* You can create a Job with just an ID (eg. when quickly processing existing Jobs like you mentioned)
* You can create a Job with NACKs and/or additional deliveries, but you don't have to (they will return zero as a default value)

The usage is then very simple, just extend the `BaseJob` and off you go.

I would also like to note that should you decide to extend `JobInterface` with `get/setBody()` due to the `JobMarshaler`, according to SemVer the library version would have to be increased to 2.0, because [any change in an interface constitutes a BC break](http://paul-m-jones.com/archives/6136). In that case I would very much ask you to consider adding the methods for those other two properties to the interface as well. I hope I have demonstrated that it would be very useful to have these basic getters and setters defined under one interface.

**Comment by mariano** [comment]
@Revisor ok I'm sold. We should in fact extend the promise and make `JobInterface` reflect a real disque job, by adding the getters for body and the other fields. Good thinking, and thanks for the thorough of your proposal.

So you can go ahead and clean up the PR if anything needs cleaning. If you feel like updating the documentation and `CHANGELOG.md` to reflect this, that'd be awesome.

**Comment by Revisor** [comment]
I will prepare a clean merge request for a code review. Since I want to still think it through a bit, prepare tests and update the documentation, I won't be able to make it today. It will be ready next week.

**Comment by mariano** [comment]
That's perfect. Thanks :)

**Comment by Revisor** [comment]
I'm sorry for the delay. I have created a pull request.
