### ISSUE TITLE
Implement JSCAN

### ISSUE THREAD

**Issue by mariano** [mariano/disque-php#26]
`JSCAN [<cursor>] [COUNT <count>] [BUSYLOOP] [QUEUE <queue>] [STATE <state1> STATE <state2> ... STATE <stateN>] [REPLY all|id]`

The command provides an interface to iterate all the existing jobs in the local node, providing a cursor in the form of an integer that is passed to the next command invocation. During the first call the cursor must be 0, in the next calls the cursor returned in the previous call is used in the next. The iterator guarantees to return all the elements but may return duplicated elements.

Options:

* `COUNT <count>` A hint about how much work to do per iteration.
* `BUSYLOOP` Block and return all the elements in a busy loop.
* `QUEUE <queue>` Return only jobs in the specified queue.
* `STATE <state>` Return jobs in the specified state. Can be used multiple times for a logical OR.
* `REPLY <type>` Job reply type. Type can be all or id. Default is to report just the job ID. If all is specified the full job state is returned like for the SHOW command.

The cursor argument can be in any place, the first non matching option that has valid cursor form of an unsigned number will be sensed as a valid cursor.

**Comment by lordlele** [comment]
Hi @mariano do you have any ETA for all new features like this?
I've just started play with Disque and I use your great library to communicate and it'll be great to have new commands available.

Otherwise, if you can point me on how to extend library to add more commands, I'll appreciate :smile:

**Comment by Revisor** [comment]
Lordlele, write a new command that implements the `\Disque\Command\CommandInterface`, register it in `\Disque\Client::__construct()` and write tests for it in `tests/Command`.
