### ISSUE TITLE
Implement PAUSE

### ISSUE THREAD

**Issue by mariano** [mariano/disque-php#27]
`PAUSE <queue-name> option1 [option2 ... optionN]`

The paused state can be set for each queue using the `PAUSE` command followed by options to specify how to change the paused state. Possible options are:

* `in`: pause the queue in input.
* `out`: pause the queue in output.
* `all`: pause the queue in input and output (same as specifying both the `in` and `out` options).
* `none`: clear the paused state in input and output.
* `state`: just report the current queue state.
* `bcast`: send a `PAUSE` command to all the reachable nodes of the cluster to set the same queue in the other nodes to the same state.

The command always returns the state of the queue after the execution of the specified options, so the return value is one of `in`, `out`, `all`, `none`.

For example, in order to block output for the queue `myqueue` in all the currently reachable nodes, the following command should be send to a single node:

```
PAUSE myqueue out bcast
```

To specify `all` is the same as to specify both `in` and `out`, so the two following forms are equivalent:

```
PAUSE myqueue in out
PAUSE myqueue all
```

To just get the current state use:

```
PAUSE myqueue state
"none"
```

**Comment by Revisor** [comment]
From the Disque docs:

* ADDJOB returns a -PAUSED error for queues paused in input.

What should happen in Disque-php? Right now `ADDJOB` on a paused queue would return `ResponseException`, if I'm not mistaken. Is that what we want? Maybe return a more specialised `QueuePausedException` in that case?

**Comment by mariano** [comment]
@Revisor same as #28 I see the need to extend `ResponseException` for some known exceptions, such as `-PAUSED` and `-LEAVING`, since they have a meaning for the client code. On this particular case for `ADDJOB` a `-PAUSED` should raise a `QueuePausedException` as you are saying, which allows for easy management in userland.

**Comment by Revisor** [comment]
Sounds good.
