### ISSUE TITLE
Change the $body in Job from array to mixed

### ISSUE THREAD

**Issue by Revisor** [mariano/disque-php#3]
Why does the `Job` body always have to be an `array`?
https://github.com/mariano/disque-php/blob/master/src/Queue/Job.php#L18

Is there a reason for the `Job` not to accept anything else? The body can safely be an integer, a string, no?

**Comment by mariano** [comment]
While a job body can be anything, `Job` in this case is a helper implementation for the most common use case (imho), where the job body is an array.

If user land code wants to use a different type of `Job`, then they can easily implement `JobInterface` and provide their own implementation as the section *Changing the Job class* exemplifies in the docs.
