### ISSUE TITLE
2.0 Release

### ISSUE THREAD

**Issue by xocasdashdash** [mariano/disque-php#32]
Hi!
I've been looking into this library and there's quite a difference between the last published stable version on packagist (1.3) and the latest one here. 
Any feature missing so you can release 2.0 ? Are you waiting for disque to release 1.0 to release your version ?

**Comment by mariano** [comment]
Nop, I'll be most likely releasing stable 2.0.1 in the next hour or so. Stay tuned :)

**Comment by mariano** [comment]
Done, [2.0.1 released](https://github.com/mariano/disque-php/releases/tag/2.0.1)

**Comment by Revisor** [comment]
Nicely done, congratulations for the milestone. :)
