### ISSUE TITLE
Update Packagist package

### ISSUE THREAD

**Issue by nailk** [mariano/disque-php#33]
If installed with Composer, disque-php GetJob command fails due to changed Job ID prefix.
It is fixed in current version on Github, so Packagist version needs to be updated.

**Comment by mariano** [comment]
I'll be most likely releasing stable 2.0.1 in the next hour or so. Stay tuned :)

**Comment by nailk** [comment]
Awesome! Mariano, please don't forget to update Packagist, it's still outdated (2015-11-03).

**Comment by mariano** [comment]
Done, [2.0.1 released](https://github.com/mariano/disque-php/releases/tag/2.0.1)
