### ISSUE TITLE
hello() and info() throw ConnectionException if called first

### ISSUE THREAD

**Issue by dwolfhub** [mariano/disque-php#38]
This script runs fine:

```
$client = new \Disque\Client([
    new \Disque\Connection\Credentials('127.0.0.1', 7711),
]);

$job = $client->queue('something')->pull(1);

var_dump($job);

// hello called after pull
var_dump($client->hello());
```

But if i try to call `hello` first, it throws a ConnectionException every time.

```
$client = new \Disque\Client([
    new \Disque\Connection\Credentials('127.0.0.1', 7711),
]);

// hello called right after client created, throws exception here
var_dump($client->hello());

$job = $client->queue('something')->pull(1);

var_dump($job);

```

Any ideas? I'm trying to write a wrapper and I'd like to be able to test the connection when I create it. I thought using `hello` or `info` would be a great way to do that, but both seem to have this issue.

**Comment by Revisor** [comment]
The short version: Call `$client->connect();` before you do anything.

The long version:
There are two ways to use Disque-PHP.
- `$client->queue('foo')->push/pull`
- `$client->addJob/getJob`

`$client->queue` is a Facade of sorts, a class that simplifies the usage of `$client`. One of the things it does for you is it automatically connects to Disque. The disadvantage of `$queue` is that it only supports some operations (see `\Disque\Queue\Queue`). You want to use one of the "advanced" Disque commands for which you must use the `Client` directly, and that means that you must also connect to Disque manually before you issue any command.

Does that make sense?

**Comment by Revisor** [comment]
Coming back to why you're doing it: 

> I'm trying to write a wrapper and I'd like to be able to test the connection when I create it.

You don't have to test the connection, the library tests that it works for you (just look at `\Disque\Connection\Manager::connect()` and go from there). It calls `hello` after every connection or a node switch, because it reveals the cluster from the hello response. You just need to catch any potential `Disque\Connection\ConnectionException` when connecting.

**Comment by dwolfhub** [comment]
Ended up using `connect` successfully. I believe I was having issues with the server when I was testing that one, but everything seems to be cleared up. I appreciate your explanation.

While I still feel that the info and hello methods shouldn't throw bad connection exceptions, you may close this ticket if you feel like this is expected functionality.

**Comment by Revisor** [comment]
Well I understand how two usage modes can be confusing, but then again, it's also described in the Readme in the first sentences

Usage
> This library provides a Queue API for easy job pushing/pulling, and direct access to all Disque commands via its Client API. If you are looking to get jobs into queues, and process them in a simple way, then the Queue API is your best choice as it abstracts Disque's internal protocol. If you instead wish to do more advanced stuff with Disque, use the Client API.

Queue
> When using the Queue API you won't need to tell the client when to connect, as it will do it automatically as needed.

Client
> When using the Client API directly (that is, using the commands provided by `\Disque\Client`), you will have to connect manually.

:)
