### ISSUE TITLE
Should Queue::pull() throw an exception if there is no job to do?

### ISSUE THREAD

**Issue by Revisor** [mariano/disque-php#8]
This is admittedly a small issue that doesn't concern the functionality, but rather best practices.

Should [`Queue::pull()`](https://github.com/mariano/disque-php/blob/master/src/Queue/Queue.php#L126) really throw an exception if there is no job to do? From all I've read, exceptions should be used sparingly and only for truly exceptional cases. If there is another clean way to relay the negative result, it should be favored over throwing an exception.

According to [this exception typology](http://blogs.msdn.com/b/ericlippert/archive/2008/09/10/vexing-exceptions.aspx), the exception thrown here would be an example of a vexing exception. It is not exceptional to not have a job ready.

What if the method just returned `null`?

What's your opinion about this in general? There might be more cases like this, but this is the place I'm working on right now and I don't want to nitpick needlessly.

**Comment by mariano** [comment]
@Revisor I agree. An exception is not the right way to go, and since we are breaking BC for the upcoming 2.0 release now is the right time to fix this

**Comment by Revisor** [comment]
First of all thank you for taking the time and getting back to me, taking a look at my questions as well as my contributions.

I have gone through the whole library and looked at the exception usage.
I have found two other places that might directly benefit from a refactoring. 

In `Disque\Client::registerCommand($command, $class)`, the exception is thrown in a situation that could be guarded via type hinting:

```php
public function registerCommand($command, $class)
{
    if (!in_array(CommandInterface::class, class_implements($class))) {
        throw new InvalidArgumentException("Class {$class} does not implement CommandInterface");
    }
    $this->commandHandlers[strtoupper($command)] = $class;
}
```
And in `Disque\Connection\Manager::setConnectionClass($class)` there is a similar case:

```php
public function setConnectionClass($class)
{
    if (!in_array(ConnectionInterface::class, class_implements($class))) {
        throw new InvalidArgumentException("Class {$class} does not implement ConnectionInterface");
    }
    $this->connectionClass = $class;
}
```

What do you think if instead of accepting the class name as an argument, the methods would accept an object of that type instead? Or, in code:

`Disque\Client::registerCommand($command, CommandInterface $commandHandler)`
`Disque\Connection\Manager::setConnection(ConnectionInterface $connection)`

The conditions would then be guarded directly by a language construct, instead of a manual check. None of the objects requires any special construction, they don't have other dependencies, so it shouldn't be a problem to create them one level higher, before calling the setter.

Whether you give me a green light just for the exception in `Queue` or for these two as well, I can prepare a pull request.

**Comment by mariano** [comment]
I agree. I was trying to save resources by not instantiating a command that
wasn't used, but the construct is negligible, so go ahead and feel free to
typehint.

And thank you for your contributions! Great work

**Comment by Revisor** [comment]
Ok, I'm on it.

And thank _you_ for such a well written library. It's a pleasure to work on it (I mean it, I read all of them before choosing this one).

**Comment by mariano** [comment]
:)
